### ISSUE TITLE
Too Complex in my opinion

### ISSUE THREAD

**Issue by StupidDan** [KingDGrizzle/Vlag-Approved-AuroraBot#1]
For me, the code abit too complex for a simple text bot, just make each command in a separate file, and then it'll be simpler to understand, and clearer to people wanting to look at your code 👍

**Comment by KingDGrizzle** [comment]
Hmm, then I'd need a commands.js file.. could do..

**Comment by KingDGrizzle** [comment]
7fb9908d719a73cc285e6ab954267300dc333ee5
