### ISSUE TITLE
where is my cOMANNDO?

### ISSUE THREAD

**Issue by annsquake** [KingDGrizzle/Vlag-Approved-AuroraBot#10]
/quake 

just.. /quake

it should show this image https://aurorame.me/i/olthd.png or go in a sequence of images ( https://aurorame.me/i/olthd.png , https://aurorame.me/i/h8618.png , https://aurorame.me/i/pp9wj.png )

**Further Details:**

uh you can add this as an emoji if you'd like https://aurorame.me/i/096a8.png

k thnx

**Comment by ffxhand** [comment]
OKhando COMMANDO ???? : O
