### ISSUE TITLE
-Josh

### ISSUE THREAD

**Issue by Scorpioner48** [KingDGrizzle/Vlag-Approved-AuroraBot#5]
**Command Name:**
-josh
**Command Aliases:**
-st1ng -sting
**Command Output:**
@st1ng#0767 has a smol lund. All hail Smol lund god.
**Further Details:**
Add or ill ban u from my meincraft server >:((((((((((((((((((
- [ ] Maintainer Only
- [ ] Contains a custom emoji
- [ ] Contains images (place links under `Further Details`)

**Comment by mrdnomaid** [comment]
+1 I would use this command
