### ISSUE TITLE
We need a bantergaming command

### ISSUE THREAD

**Issue by BanterGaming** [KingDGrizzle/Vlag-Approved-AuroraBot#7]
**Command Name:**
-bantergaming
**Command Aliases:**
-banter -eggs
**Command Output:**
i like eggs 
**Further Details:**
- [ ] Maintainer Only
- [ ] Contains a custom emoji
- [ ] Contains images (place links under `Further Details`)

**Comment by KingDGrizzle** [comment]
You already requested it once
